# ワークフローの名前
name: Deploy HTML from GCF to Firebase Hosting

# ワークフローをトリガーするイベントを設定
on:
  # スケジュール実行を設定 (例: 毎日 午前0時 UTC に実行)
  # cron形式で指定します。詳細はこちらを参照: https://crontab.guru/
  schedule:
    - cron: '0 6 * * *' # 毎日 UTC 6:00 (日本時間 15:00) に実行
  # 手動実行も可能にする場合
  workflow_dispatch:

# ワークフローで実行するジョブを定義
jobs:
  deploy:
    # ジョブを実行する環境
    runs-on: ubuntu-latest

    # ジョブのステップ
    steps:
      # リポジトリをチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v4

      # Pythonをセットアップ
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x' # 使用するPythonのバージョンを指定

      # 必要なPythonライブラリをインストール
      # GCFを呼び出すためのrequestsライブラリが必要です
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      # GCFを呼び出し、HTMLを取得してファイルに保存するスクリプトを実行
      # このステップで使用するPythonスクリプトは別途作成します
      - name: Fetch HTML from GCF and save
        run: python fetch_and_save_html.py

      # Firebase CLIをセットアップ（pocket-apps/action-setup-firebaseを使用）
      # FirebaseプロジェクトIDとCIトークンが必要です
      - name: Setup Firebase CLI using Token
        uses: pocket-apps/action-setup-firebase@v2
        with:
          # GitHub Secretsに保存したFirebase CIトークンを指定
          # 事前にGitHubリポジトリの設定でSecretsに FIREBASE_CI_TOKEN という名前で登録してください
          firebase-token: ${{ secrets.FIREBASE_CI_TOKEN }}
          # プロジェクトIDもここで指定（デプロイコマンドでも使用）
          projectID: sample-d6924 # ここは既に設定済みかと思います

      # Firebase Hostingにデプロイ
      # publicディレクトリ内のファイルがデプロイされます
      - name: Deploy to Firebase Hosting
        # firebase deploy コマンドに --project オプションを追加してプロジェクトIDを明示的に指定
        run: firebase deploy --only hosting --project sample-d6924
        # もしプロジェクトIDをSecretsに登録している場合は、以下のように記述することも可能
        # run: firebase deploy --only hosting --project ${{ secrets.FIREBASE_PROJECT_ID }}
        # デプロイ対象のディレクトリを指定する必要がある場合 (デフォルトはpublic)
        # run: firebase deploy --only hosting --project YOUR_FIREBASE_PROJECT_ID --public=./path/to/your/public/directory

